{
 "title": "Covid-19 Italy",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last_date",
    "query": "SELECT top 1 convert(varchar(10),cast(dateadd(second,ts/1000,'19700101') as date)) from covid_data.dbo.pcm_dpc_italy order by ts desc"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "SELECT readableName __text, columnName __value \nFROM (VALUES\n\t('totalPositiveCases','Total Positive Cases'),\n\t('newPositiveCases','New Positive Cases'),\n\t('currentPositiveCases', 'Current Positive Cases'),\n\t('newCurrentPositiveCases','New Current Positive Cases'),\n\t('deaths','Deaths'),\n\t('recovered', 'Recovered'),\n\t('homeConfinement','Home Confinement'),\n\t('totalHospitalised','Total Hospitalised'),\n\t('hospitalisedWithSymptoms','Hospitalised With Symptoms'),\n\t('intensiveCare','Intensive Care'),\n\t('testsPerformed','Tests Performed')\n\t) t1 (columnName,readableName) "
   },
   {
    "name": "region",
    "label": "Region",
    "query": "SELECT regionName FROM pcm_dpc_regions ORDER BY regionName"
   },
   {
    "name": "last_ts",
    "query": "select top 1 ts from pcm_dpc_regions order by ts desc"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\nData updated to the **$last_date**"
  },
  {
   "title": "Italy - global report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ntotalpositivecases\nfrom pcm_dpc_italy\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ncurrentpositivecases\nfrom pcm_dpc_italy\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ndeaths\nfrom pcm_dpc_italy\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "Deaths / Total cases",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ndeaths * 100.0 / totalPositiveCases\nfrom pcm_dpc_italy\nwhere ts = $last_ts"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\nrecovered\nfrom pcm_dpc_italy\n"
      }
     ]
    },
    {
     "title": "Total cases by Region",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "select\n1586004872 as time,\nregionname,\ntotalpositivecases\nfrom pcm_dpc_regions\nwhere ts = $last_ts\norder by totalpositivecases desc\n\n\n\n"
      }
     ]
    },
    {
     "title": "Deaths by Region",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "rawSql": "select\n1586004872 as time,\nregionname,\ndeaths\nfrom pcm_dpc_regions\nwhere ts = $last_ts\norder by totalpositivecases desc\n\n\n"
      }
     ]
    },
    {
     "title": "Recovered by Region",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "rawSql": "select\n1586004872 as time,\nregionname,\nrecovered\nfrom pcm_dpc_regions\nwhere ts = $last_ts\norder by recovered desc\n\n\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ntestsperformed\nfrom pcm_dpc_italy\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "Tests performed / Total cases",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 28 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ntotalPositiveCases * 100.0 / testsperformed\nfrom pcm_dpc_italy\nwhere ts = $last_ts"
      }
     ]
    },
    {
     "title": "Regions details",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "\n\nselect\nregionName as Region,\ncurrentPositiveCases as \"Current positives cases\",\ntotalPositiveCases as \"Total positive cases\",\ntestsPerformed as \"Tests performed\",\ndeaths as \"Deaths\",\nrecovered as \"Recovered\",\nhomeConfinement as \"Home confinement\",\ntotalHospitalised as  \"Total Hospitalises\",\nhospitalisedWithSymptoms as \"Hospitalised with symptoms\",\nintensiveCare as \"Intensive Care\"\nfrom pcm_dpc_regions\nwhere ts = 1587427200000\norder by regionname desc"
      }
     ]
    }
   ]
  },
  {
   "title": "Italy - daily data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
     "repeat": "metric",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_italy\nwhere $__unixEpochFilter(ts/1000)\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_italy \n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    }
   ]
  },
  {
   "title": "$region - details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ntotalpositivecases\nfrom pcm_dpc_regions\nwhere regionname = '$region'\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ncurrentpositivecases\nfrom pcm_dpc_regions\nwhere regionname = '$region'\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ndeaths\nfrom pcm_dpc_regions\nwhere regionname = '$region'"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "Deaths / Total cases",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ndeaths * 100.0 / totalPositiveCases\nfrom pcm_dpc_regions\nwhere ts = $last_ts\nand regionname = '$region'"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\nrecovered\nfrom pcm_dpc_regions\nwhere regionname = '$region'\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ntestsperformed\nfrom pcm_dpc_regions\nwhere regionname = '$region'\n"
      }
     ]
    },
    {
     "type": "singlestat",
     "description": "Tests performed / Total cases",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\ntotalPositiveCases * 100.0 / testsperformed\nfrom pcm_dpc_regions\nwhere ts = $last_ts\nand regionname = '$region'\n"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
     "repeat": "metric",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "$metric",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 169 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\n  ts as time,\n  ${metric:csv} as \"Daily data\"\nfrom pcm_dpc_regions\nwhere $__unixEpochFilter(ts/1000)\nand regionname='$region'\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom pcm_dpc_regions\n\twhere $__unixEpochFilter(ts/1000)\n\tand regionname='$region'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    }
   ]
  }
 ]
}