{
 "title": "Covid-19",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric", "query": "Cases, Deaths" },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT replace(country,'_',' ') __text, geoid __value from daily_global order by country"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "select\nts as time,\nsum(cases)\nfrom daily_global\ngroup by ts\norder by ts"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "rawSql": "select\nts as time,\nsum(deaths)\nfrom daily_global\ngroup by ts\norder by ts"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "select\nsum(deaths) * 100.0 / sum(cases)\nfrom daily_global\n"
      }
     ]
    },
    {
     "title": "Total Cases",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 10 },
     "valueName": "total",
     "targets": [
      {
       "rawSql": "SELECT\n  ts as time,\n  sum(cases) as value,\n  geoId\nFROM\n  daily_global\ngroup by geoId,ts"
      }
     ]
    },
    {
     "title": "Countries Details",
     "type": "table",
     "gridPos": { "h": 28, "w": 13, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "select\n  REPLACE(country,'_',' ') as Country,\n  sum(cases) as Cases,\n  sum(deaths) as Deaths,\n  sum(deaths) * 100.0 / sum(cases) as \"Mortality Rate\"\nfrom daily_global\ngroup by country \norder by cases desc"
      }
     ]
    },
    {
     "title": "Top 10 Country by Cases",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 11, "x": 13, "y": 32 },
     "targets": [
      {
       "rawSql": "\nselect\n1586004872 as time,\nreplace(country,'_',' '),\nsum(cases) as cases\nfrom (\n\tselect\n\tts,\n\tsum(cases) as cases,\n\tcountry\n\tfrom daily_global\n\tgroup by country,ts\n\t) as a\ngroup by country\norder by cases desc\n\n"
      }
     ]
    },
    {
     "title": "Top 10 Country by Deaths",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 11, "x": 13, "y": 46 },
     "targets": [
      {
       "rawSql": "\nselect\n1586004872 as time,\nreplace(country,'_',' '),\nsum(deaths) as deaths\nfrom (\n\tselect\n\tts,\n\tsum(deaths) as deaths,\n\tcountry\n\tfrom daily_global\n\tgroup by country,ts\n\t) as a\ngroup by country\norder by deaths desc\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Daily $metric Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "metric",
   "collapsed": true,
   "panels": [
    {
     "title": "New Daily $metric (Linear Scale)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\nsum(${metric:csv}) as \"New Daily ${metric:csv}\",\nts as time\nfrom daily_global\nwhere $__unixEpochFilter(ts/1000)\ngroup by ts\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 29, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "New Daily ${metric:csv} (Logarithmic Scale)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\nsum(${metric:csv}) as \"New Daily ${metric:csv}\",\nts as time\nfrom daily_global\nwhere $__unixEpochFilter(ts/1000)\ngroup by ts\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 29, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "Daily Increase",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "with t1 as\n(\n\t\tselect\n\t\t\tsum(${metric:csv}) as ${metric:csv},\n\t\t\tts as time\n\t\tfrom daily_global\n\t\twhere $__unixEpochFilter(ts/1000)\n\t\tgroup by ts\n),\nt2 as\n(\n\tselect time,\n\t\t${metric:csv},\n\t\t LAG(${metric:csv},1) OVER (\n\t\t \tORDER BY time \n\t\t ) ${metric:csv}Prev\n\tfrom t1\n)\nselect\ntime,\n${metric:csv}-COALESCE (${metric:csv}Prev,0) as \"Daily Increase\"\nfrom t2\norder by time"
      }
     ]
    },
    {
     "title": "Percentage Change",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "with t1 as\n(\n\t\tselect\n\t\t\tsum(${metric:csv}) as ${metric:csv},\n\t\t\tcast(dateadd(second,ts/1000,'19700101') as date) as time\n\t\tfrom daily_global\n  where $__unixEpochFilter(ts/1000)\n\t\tgroup by ts\n),\nt2 as\n(\n\tselect time,\n\t\t${metric:csv},\n\t\t LAG(${metric:csv},1) OVER (\n\t\t \tORDER BY time \n\t\t ) ${metric:csv}Prev\n\tfrom t1\n)\nselect\ntime,\ncase\n\twhen \t${metric:csv}Prev is null then null\n\twhen\t${metric:csv}Prev = 0 then null\n\telse \t(${metric:csv}-${metric:csv}Prev)*100.0/${metric:csv}Prev\nend \"Percentage Change\"\nfrom t2\norder by time"
      }
     ]
    }
   ]
  },
  {
   "title": "Daily $metric Details - $country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "metric",
   "collapsed": true,
   "panels": [
    {
     "title": "New Daily $metric (Linear Scale)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\nsum(${metric:csv}) as \"New Daily ${metric:csv}\",\nts as time\nfrom daily_global\nwhere $__unixEpochFilter(ts/1000)\nand geoid = '$country'\ngroup by ts\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tand geoid = '$country'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tand geoid = '$country'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 29, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "New Daily ${metric:csv} (Logarithmic Scale)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "select\nsum(${metric:csv}) as \"New Daily ${metric:csv}\",\nts as time\nfrom daily_global\nwhere $__unixEpochFilter(ts/1000)\nand geoid = '$country'\ngroup by ts\norder by ts"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tand geoid = '$country'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 5 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 4, MAVG, NULL) \"Moving AVG 5\"\nfrom T2\norder by date"
      },
      {
       "rawSql": "with T1 as (\n\tselect\n\t\tROW_NUMBER() OVER (ORDER BY ts ASC) RowNumber,\n\t\tcast(dateadd(second,ts/1000,'19700101') as date) as Date,\n\t\tsum(${metric:csv}) as ${metric:csv}\n\tfrom covid_data.dbo.daily_global dg\n\twhere $__unixEpochFilter(ts/1000)\n\tand geoid = '$country'\n\tgroup by ts\n),\nT2 as (\n\tselect\n\tRowNumber,\n\tdate,\n\tavg(${metric:csv}) over (order by date asc rows 30 PRECEDING ) as MAVG\n\tfrom T1\n)\nselect\n\tdate as time,\n\tIIF(RowNumber > 29, MAVG, NULL) \"Moving AVG 30\"\nfrom T2\norder by date"
      }
     ]
    },
    {
     "title": "Daily Increase",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "with t1 as\n(\n\t\tselect\n\t\t\tsum(${metric:csv}) as ${metric:csv},\n\t\t\tts as time\n\t\tfrom daily_global\n\t\twhere $__unixEpochFilter(ts/1000)\n\t\tand geoid = '$country'\n\t\tgroup by ts\n),\nt2 as\n(\n\tselect time,\n\t\t${metric:csv},\n\t\t LAG(${metric:csv},1) OVER (\n\t\t \tORDER BY time \n\t\t ) ${metric:csv}Prev\n\tfrom t1\n)\nselect\ntime,\n${metric:csv}-COALESCE (${metric:csv}Prev,0) as \"Daily Increase\"\nfrom t2\norder by time"
      }
     ]
    },
    {
     "title": "Percentage Change",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "with t1 as\n(\n\t\tselect\n\t\t\tsum(${metric:csv}) as ${metric:csv},\n\t\t\tcast(dateadd(second,ts/1000,'19700101') as date) as time\n\t\tfrom daily_global\n  where $__unixEpochFilter(ts/1000)\n  and geoid = '$country'\n\t\tgroup by ts\n),\nt2 as\n(\n\tselect time,\n\t\t${metric:csv},\n\t\t LAG(${metric:csv},1) OVER (\n\t\t \tORDER BY time \n\t\t ) ${metric:csv}Prev\n\tfrom t1\n)\nselect\ntime,\ncase\n\twhen \t${metric:csv}Prev is null then null\n\twhen\t${metric:csv}Prev = 0 then null\n\telse \t(${metric:csv}-${metric:csv}Prev)*100.0/${metric:csv}Prev\nend \"Percentage Change\"\nfrom t2\norder by time"
      }
     ]
    }
   ]
  }
 ]
}